[project]
name = "streamlit_fragments"
version = "0.1.0"
description = "Add a short description here"
authors = ["hampus.londogard@gmail.com <hampus.londogard@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
simple = "streamlit run src/main.py"
complex = "streamlit run src/complex_main.py"

[dependencies]
python = ">=3.12.7,<3.13"
streamlit = ">=1.33.0,<1.34"
polars = ">=0.20.21,<0.21"
pandas-datareader = ">=0.10.0,<0.11"
hvplot = ">=0.9.2,<0.10"
yfinance = ">=0.2.38,<0.3"
plotly = ">=5.21.0,<5.22"
dataset = ">=1.6.2,<1.7"
ray-data = ">=2.37.0,<2.38"

[pypi-dependencies]
getdaft = "*"
